### PR TITLE
Feat/UI refresh

### LINKED ISSUE #153: UI Redesign
See https://www.figma.com/file/GbaNfilKtcB2xBaog6fKzO/MewsFeed?type=design&node-id=0-1&t=wRpShEXe46ttoffl-0

- We will use the sidebar design without labels, just icons
- Search button will open search in a modal
- style list views the same as feed view

### PR DESCRIPTION
**Pull request by mattyg**
Resolves #153 
Resolves part of #101

### CODE REVIEW

**Comment by jost-s** [comment]
Oh lord, another tiny PR! =D

The avatar button looks as if it covered something
image

**Comment by jost-s** [comment]
The profile popup could be narrower by default
image

**Review by jost-s — APPROVED** [review]
L fuckinamazing TM!

**Comment by bierlingm** [comment]
Screenshot 2023-07-05 at 11 50 47 AM

Looks like the same small issues Jost has already identified, except that I would add that the "+" sign in the avatar image upload isn't centered, and the "save profile" text isn't centered either.

Once I clicked save profile, this is what I see:

Screenshot 2023-07-05 at 11 53 10 AM

Here's what the console says:

Screenshot 2023-07-05 at 11 53 45 AM

Screenshot 2023-07-05 at 11 54 07 AM

I closed the window and opened it again and it worked again.

Screenshot 2023-07-05 at 11 54 55 AM

Man, it's so gorgeous!!!

**Comment by bierlingm** [comment]
Screenshot 2023-07-05 at 12 12 26 PM

The line above the "Barcelona, Spain" looks a bit strange. Not sure it's necessary, or if it is, perhaps play around with its thickness or color?

---

Once I click on the profile that pops up when I hover over the user avatar, it sent me to the profile and briefly it looked like this:

Screenshot 2023-07-05 at 12 14 07 PM

---

Screenshot 2023-07-05 at 12 16 48 PM

On the view above, when I click on the mew that I pinned (the lower one), it takes me to this view which is (I think erroneously) called yarn:

Screenshot 2023-07-05 at 12 18 13 PM

I guess we are calling any mew that has replies on it a yarn?

If so, let's make sure we understand how that impacts future development. My original understanding of it was that it's effectively our version of Twitter's "threads" combined with its "pins", in that it's a way you can have multiple pieces of content shown in an ongoing line/view and displayed as important on your profile. Twitter does it not really as a feature, but rather users hacked the reply feature to create what people now understand as threads. It does have pins, or rather just one pin, and now they added highlights which basically allow you to do what we wanted to do with yarns: display 2 or more of those as things at the top of the profile, and have the ability to add future mews to the yarn even when it's a separate mew and not actually created as a reply to the initial mew that starts the yarn.

**Comment by bierlingm** [comment]
Screenshot 2023-07-05 at 12 29 04 PM

I don't quite understand how the link constructor works, and if I don't, I imagine others won't either, since I have never encountered the pattern before.

I'm familiar with the pattern of [text](link) from markdown, so we could do that, or we just don't use it at all.

**Comment by bierlingm** [comment]
Screenshot 2023-07-05 at 12 30 59 PM

I just clicked the retweet (mewmew) on the original one at the top, and then the mewmew showed up as a reply underneath. Is that intended behavior?

Also, it would be great if we give people feedback that they have in fact mewmewed the mew they intended to mewmew by changing (lighting up) the icon for it, similar to Twitter, like this:

Screenshot 2023-07-05 at 12 33 14 PM

**Comment by bierlingm** [comment]
I'm also wondering whether something strange is going on, because I installed the new version with the recommended seed 'internal-testing' and I can find my profile from the other installed version without that seed in the search results.

Screenshot 2023-07-05 at 12 34 13 PM

May I be misinterpreting what's going on?

**Comment by mattyg** [comment]
> It does have pins, or rather just one pin, and now they added highlights which basically allow you to do what we wanted to do with yarns: display 2 or more of those as things at the top of the profile, and have the ability to add future mews to the yarn even when it's a separate mew and not actually created as a reply to the initial mew that starts the yarn.

Okay yeah previously the yarn page was implemented as just showing all the replies to the mew. I did not understand this was the intention for this feature. We may need to discuss sync how we want the UX to work for this feature, or alternatively scrap it from this release and implement with proper attention down the road.

**Comment by mattyg** [comment]
> I don't quite understand how the link constructor works, and if I don't, I imagine others won't either, since I have never encountered the pattern before.

You type `^mylabel` a popup appears, and you paste the link into that popup. We had a discussion about the functionality during a meeting months ago and decided to go with this pattern. We can bring it up again if we want to consider altering / removing it.

**Comment by mattyg** [comment]
> I just clicked the retweet (mewmew) on the original one at the top, and then the mewmew showed up as a reply underneath. Is that intended behavior?

Yes the current behavior of the yarn view is to show all responses underneath (mewmews, replies, quotes), which was my understanding of the yarn page feature. though its currently not showing the text `mewmewed from @blah` on the yarn page which should be changed.

**Comment by mattyg** [comment]
> I'm also wondering whether something strange is going on, because I installed the new version with the recommended seed 'internal-testing' and I can find my profile from the other installed version without that seed in the search results.

huh, I'm not able to reproduce that. Can you double-check the settings page of launcher and confirm that they have 2 different network seeds?

**Comment by mattyg** [comment]
Okay I went through and implemented nearly all the requested revisions. Below is my log of all the revisions and the person who requested them:

David:

- [x] make site menu buttons pure black 

- [x] reduce width of content area of pages to ~700px

- [x] fix width + height of icons

- [x] ensure all icons have same line thickness

- [x] avatar icon slightly bigger than others

- [x] display response yarn links above agent avatar + name, move timestamp up to match

- [x] mew response buttons gray, black on hover, remove button outline

- [x] make permanent Create Mew field overlay less-permanent

  - ```
    potential update options
    
        showing it only on the HOME view
        make it hide/show on scrolls
        hide it all-together under a NEW MEW button (like it's done on mobile). Button located in the left side menu below PROFILE. With a bigger spacer than the rest of the menu buttons
    ```

    **I implemented showing the input field on the feed page, hiding it on other pages and instead showing a 'create mew' button**

- [x] make Create Mew input background color #000 with 4% opacity

- [x] create mew input: make background more rounded

- [x] remove all drop shadows (create mew input, agent profile popup)

- [x] left padding of title 'mewsfeed' to align with avatar

- [x] agent profile popup: reduce thickness & change color of horizontal line

- [x] agent profile popup: expand to fill width if required by content

- [x] lighten background overlay of dialogs

- [x] agent profile page: increase left margin, increase top margin

- [x] agent profile page detail section: decrease horizontal padding

- [x] agent profile page detail section: lighten background

- [x] agent profile page: hide 'pinned' list entirely if no mews pinned

- [x] agent profile page detail section: add 'switch theme' button

- [x] for dark mode use high contrast pure black and white

- [x] remove back button on Explore and Notifications page 

- [ ] bigger & in style version of "send mew"

  **not sure what this means**

- [x] agent profile page detail section: bigger padding of buttons

## Jost

- [x] Create Profile / Edit profile - avatar button has a empty block half behind it
- [x] profile popup narrower by defaul

### Moritz

- [x] Create Profile / Edit profile - avatar button plus sign not centered

- [x] Create Profile / Edit profile - save profile text not centered

- [x] Create Profile -- after creation, dialog hides but doesn't close, error in console, on refresh profile is created


- [x] reduce thickness of lines in base profile detail

- [ ] replace url input form with markdown-based links OR remove entirely

  - **needs more discussion / clarification**

- [x] agent profile page: briefly profile detail not shown when profile not loaded yet

- [x] Also, it would be great if we give people feedback that  they have in fact mewmewed the mew they intended to mewmew by changing  (lighting up) the icon for it, similar to Twitter, like this:

- [ ] Search results from a different app instance (the old version installed with no network seed) are showing up the new app instance (the new version with network seed `internal-testing`)

  **not able to reproduce, need more info / confirmation**


**Matt**

- [x] yarn link button should be disabled on yarn page responses

**Comment by bierlingm** [comment]
As requested, here's the last round of things I'll give feedback on.

Screenshot 2023-07-11 at 10 10 43 AM

Looks like you can retweet something multiple times. Not sure that's expected or desired behavior. It certainly breaks with the Twitter convention. The way people retweet something multiple times over there is with a quote tweet and then leaving the text field empty. We can allow that, if we want to, or we can just actually only allow a "bare retweet" once.

Matt, what do you think?

I kind of like the idea of only allowing one "regular comment-free retweet", at least through the UI. It encourages less mindless reproduction and more considered engagement and response.

Screenshot 2023-07-11 at 10 32 07 AM

Notifications didn't show up. Not sure why.

Screenshot 2023-07-11 at 10 32 52 AM

Also the notification bell doesn't return to a "clean slate" when I click on it.

That reminds me: let's not let the notification counter go too high. Shall we cap it at 20 and then just say "20+", like Twitter?

Screenshot 2023-07-11 at 10 50 02 AM

Looks like it has some problem with updating the notifications counter.

Here are the errors in the console:

Screenshot 2023-07-11 at 10 51 25 AM

Something about a promise rejection?

Screenshot 2023-07-11 at 10 34 50 AM

Tried searching for the content of a mew I made and it doesn't show anything. Did we decide to only show search results for people or also for mews?

Screenshot 2023-07-11 at 10 36 21 AM

For some reason the profile doesn't show the profile contents sometimes when navigating there, which seems strange since that's information that should be readily available from local data.

Screenshot 2023-07-11 at 10 37 11 AM

Looks like it does show up after a little though. Are we caching it? If not, maybe we should add it to what we cache?

Screenshot 2023-07-11 at 10 37 50 AM

The "copied" thing that appears after clicking on the identicon shows up in a slightly weird spot off to the left.

Screenshot 2023-07-11 at 10 38 45 AM

On mobile view too, although less far away.

Screenshot 2023-07-11 at 10 39 18 AM

Hovering over the question mark icon under the mew text box shows a cut off info text. Looks like it's contained within the mew window which leads to it getting cut off.

Screenshot 2023-07-11 at 10 40 22 AM

Same for the non-mobile, desktop view, albeit more is visible.

Screenshot 2023-07-11 at 10 41 24 AM

Maybe we want to line up (left align?) the "following" and "follower" counts with the place and join date things below? Or the other way around.

Screenshot 2023-07-11 at 10 42 57 AM

A deleted pinned tweet stays pinned – interesting... I think this isn't necessarily undesirable behavior. Shall we leave it like that?

Screenshot 2023-07-11 at 10 44 27 AM

When I quote mew the mew, the quote mew counter doesn't go up higher than 1.

Screenshot 2023-07-11 at 10 45 13 AM

There is a slightly too large gap between the "quoted" and "Maurice" parts of "Quoted Maurice", and conversely too little space between "@bierlingm" and "(Deleted)".

Screenshot 2023-07-11 at 10 47 25 AM

When my cursor hovers over the mew, it only switches to the hand from the pointer on select portions. Perhaps we can make it switch to the hand everywhere, or at least on more clickable and navigatable-to parts than just the text of the quoted mew or the quote marks?

---

I think this is about as much as I can find for the moment.

**Comment by dfrml** [comment]
Great work @mattyg ! Love how you implemented the NEW MEW functionality! 🙏 

👇 Things I encountered. Prioritize at your own discretion.

## Home on empty state
- [ ] fix: in empty state I could not view the HOME page. 
Screenshot 2023-07-10 at 13 57 15




## Home
- [ ] fix: URL link formatted right, but doesn't open anything
- [ ] fix: make the text + icon black in the NEW MEW MODAL. Hard to read now.
Screenshot 2023-07-11 at 18 41 47




## Profile
- [ ] fix: make the separation lines black instead of white (as well as the line in the HOVER PROFILE MODAL)
- [ ] fix: same padding in all directions (now top more than sides)
- [ ] fix: less padding in the bottom two rows (follower count and location). to be more compact
- [ ] fix: the profile button in the left menu seems to have tiny top border when active. could have a black inside border of 5px.
Screenshot 2023-07-10 at 13 59 03

**Comment by jost-s** [comment]
This be a fix for Guillem rather than you
image

**Comment by jost-s** [comment]
I suggest to make the whole row a link to get a user profile
image

**Comment by mattyg** [comment]
Revisions requested by Art at meeting today:
- lick icon should turn red on hover instead of black

Revisions requested by Jost at meeting today:
- remove notifications for actions on your own mews

- use original logo as favicon for now

**Comment by mattyg** [comment]
Okay I went through and resolved nearly all of the second round of revisions. Just one I couldn't reproduce and a few others I made slightly different changes than requested.

Once this passes CI I'm going to merge it. Thanks everyone for the feedback and thanks a ton @dfrml for the design!

Moritz:

- [x] A user should only be able to mewmew each mew once
- [x] notifications didn't show up
- [x] notifications count doesn't reset when visiting notifications page
  - **can't reproduce -- i think it's fixed**
- [x] cap number of notifications at 20+
- [x] console error on notifications page: 
- [x] Profile page: loading display of profile details for a long time even when you've already fetched the data -- it should be cached
- [x] agent-avatar "copied" tooltip rendered absolute on the left side of the sreen
- [x] create mew dialog: help tooltip cut off by dialog window
- [x] on profile page: add left margin to  "location + joined date to match "following" and "follower" buttons
- [ ] quote mew count doesn't go higher than 1
  - **can't reproduce**
- [x] response yarn button: uniform spacing between all words
- [x] cursor hand when mousing over entire mew in quote mew

David: 

- [x] fix: in empty state I could not view the HOME page.
  ​	**Changed to allow users to navigate to feed page even if they are not following anyone, but upon visiting the '/' url route, they will still be redirected to the explore page if they are not following anyone**
- [x] fix: URL link formatted right, but doesn't open anything
- [x] create mew input: make placeholder text black
  ​	- **made it dark enough to be visible, but not completely black**

  profile page:

- [x] fix: make the separation lines black instead of white (as well as the line in the HOVER PROFILE MODAL)
- [x] fix: same padding in all directions (now top more than sides)
- [x] fix: less padding in the bottom two rows (follower count and location). to be more compact
- [x] fix: the profile button in the left menu seems to have tiny top border when active. could have a black inside border of 5px.
  - **made border more distinctive, not inset**

Jost:

- [x] Make entire profile row clickable in following / follower dialog
- [x] remove notifications for actions on your own mews

Art:

- [x] lick icon should turn red on hover instead of black
- [x] Replace "new mew" button text / icon to more clearly distinguish  from "mew mew" -- change text to just "Mew", replace chat icon with a  plus icon

Matt:

- [x] deleted mew: drop 'deleted timestamp' to new line, make text red
- [x] add more bottom padding to all pages in mobile viewports
- [x] create mew input help tooltip -- position to the right on small screens, 
- [x] replace tooltip to ensure it doesn't overflow screen in small viewports, causing scroll bar
- [x] creating an original mew via dialog redirects you to feed page 2n
- [x] change initial loading indicator of discover mews list

**Pull request merged**
