### PR TITLE
Link to mentions on profile

### LINKED ISSUE #66: (Ability to) view all mentions of an Agent on their profile page

### PR DESCRIPTION
**Pull request by mattyg**
Resolves #66 

**Overview**
- Adds link "Mew Mentions" to agent profile page, pointing to mention tags page for that agent
- Change mention page route to `/mention/:tag/:agentPubKey`
- Fix bug where clicking on profile in profile popup on a mention navigates to profile page, then to mention page
- Minor refactoring for clarity, simplicity

The styling of the Mention page link doesn't really feel right, but I'm not sure what to use instead.

### CODE REVIEW

**Review by jost-s — CHANGES_REQUESTED** [review]
I create two mews where one mentions user aaa and the other mentions user aaa and user bbb. On aaa's profile I click on "mew mentions" and see both mews. When I click then on bbb, the title changes to "bbb's mew mentions" but there are still both mews where I expect only one to be.

I suppose you need to watch the route.

image


And an unrelated bug:
When I enter "@someusername" and the popup appears, I hit the down arrow which highlights the first option, but when I press return to confirm, the option isn't selected but instead there's a line feed in the input field
image

**Comment by jost-s** [comment]
Another unrelated problem, in my Launcher window the app doesn't load and I get the SyntaxError: Invalid regular expression: invalid group specifier name

for the URL regex
```typescript
const RAW_URL_REGEX = /(?:(?<!\^)\b(?:(?:[a-z][\w-]+:(?:\/{1,3}|[a-z0-9%])|[a-z0-9.-]+[.][a-z]{2,4}\/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()[\]{};:'".,<>?«»“”‘’])))/;
```

**Comment by mattyg** [comment]
> Another unrelated problem, in my Launcher window the app doesn't load and I get the SyntaxError: Invalid regular expression: invalid group specifier name

thanks I created a new ticket #114

**Comment by mattyg** [comment]
> When I enter "@Someusername" and the popup appears, I hit the down arrow which highlights the first option, but when I press return to confirm, the option isn't selected but instead there's a line feed in the input field

I can't seem to reproduce this issue @jost-s -- is it still occurring if you pull the latest changes? What browser are you running? Are you pressing the "Enter" key (in main keyboard) or the "Return" key (on numpad).

**Comment by jost-s** [comment]
> I can't seem to reproduce this issue @jost-s -- is it still occurring if you pull the latest changes? What browser are you running? Are you pressing the "Enter" key (in main keyboard) or the "Return" key (on numpad).

It only happens in an emergent dialog for, say, creating a mew or replying to one.

**Comment by jost-s** [comment]
A new bug (I don't know when it was introduced):
A profile popup should be shown as long as it's hovered with the mouse. It disappears after a timeout despite hovering.

**Review by jost-s — APPROVED** [review]
Jumping from one mentions page to another works now

**Comment by mattyg** [comment]
>  A profile popup should be shown as long as it's hovered with the mouse. It disappears after a timeout despite hovering.

fixed

> It only happens in an emergent dialog for, say, creating a mew or replying to one.

huh, still can't seem to reproduce it. I think I'm going to merge for now since the other PRs are making changes to the same areas, I'll see if I can reproduce it in those.

**Pull request merged**
