### PR TITLE
Mew input & content display improvements

### LINKED ISSUE #48: Limiting Mew Text Length
Currently, mew text is limited to 200 characters in validation rules. Let's add that limit to the UI CreateMewField.

### LINKED ISSUE #49: [UI] Add profile popup for mentions
Add a popup with the agent profile when user hovers a mention in a mew

### LINKED ISSUE #53: [UI] Enable multi-line mews

### LINKED ISSUE #55: [UI] [bug] URL links without title are not clickable
image
The link in the displayed mew should be clickable and open in a new tab.

### PR DESCRIPTION
**Pull request by mattyg**
I'm just going to pull all these mew input / content display changes into this one PR -- otherwise there will be a bunch of merge conflicts later.

Hopefully I caught all the weird edge-cases!

Resolves #55 

Resolves #49 

Resolves #48 
- CreateMewField restricts input to 200 characters
- Display number of characters beneath field
- Count excludes trailing whitespace and new lines (which will be trimmed)

Resolves #53 
- User can create a line-break in a mew with Enter
- User cannot input a leading line-break
- User cannot input more than 3 consecutive line-breaks
- Each line-break is included in the character count (excluding trailing line-breaks)
- Add support for 'Tab' key to select first agent tag in list
- Cleanup and clarifying comments for input key handling

### CODE REVIEW

**Comment by mattyg** [comment]
Okay I think I caught all the edge-cases. This time it's *actually* ready for review.

**Comment by jost-s** [comment]
Cheers bro, I love it!

An issue with the input field:
I can't post with 200 characters, button disabled. 199 is fine.
image

image

**Comment by jost-s** [comment]
When the  allowed num of characters is exceeded because of a mention, publish button should be disabled or mention completion shouldn't happen or when publishing it should return an error message. What happens currently is that the mew is not created and there's no user feedback.
image


image

**Comment by jost-s** [comment]
Anchors in links include the `^` now and are broken. I can click on links without titles, but the URL includes the ^.
image

**Review by jost-s — CHANGES_REQUESTED** [review]
Some more weird edge cases =)

Character limit works really well! Profile popup on mention hover works too.

**Comment by mattyg** [comment]
> An issue with the input field: I can't post with 200 characters, button disabled. 199 is fine. image

I believe this is correct behavior: in the screenshot it shows too many characters (202 / 200) so the button should be disabled. The UX is a little odd because leading & trailing linebreaks are *not* counted as characters, but interior linebreaks *are* counted. So when you enter a few trailing linebreaks, the character count doesn't increase, but then when you start typing it jumps up to include those linebreaks.

**Comment by mattyg** [comment]
> When the allowed num of characters is exceeded because of a mention, publish button should be disabled or mention completion shouldn't happen or when publishing it should return an error message. What happens currently is that the mew is not created and there's no user feedback. 

Good catch -- fixed to include mentions in the character count.

**Comment by mattyg** [comment]
> Anchors in links include the `^` now and are broken. I can click on links without titles, but the URL includes the ^.

Another good catch -- fixed so that raw urls prefaced by a '^' character are *not* treated as urls.

**Comment by jost-s** [comment]
> > An issue with the input field: I can't post with 200 characters, button disabled. 199 is fine. image
> 
> I believe this is correct behavior: in the screenshot it shows too many characters (202 / 200) so the button should be disabled. The UX is a little odd because leading & trailing linebreaks are _not_ counted as characters, but interior linebreaks _are_ counted. So when you enter a few trailing linebreaks, the character count doesn't increase, but then when you start typing again the count jumps up to include those linebreaks.

Sure, that's correct. I don't know what I have seen there, but the screenshot doesn't show a bug. I can't reproduce a problem with this anymore in any case. I've understood how the spaces are handled.

**Comment by jost-s** [comment]
The URL bug is still there. Perhaps I didn't explain it well, when you write a URL like `^https://www.brave.com` and then do not enter a title and create the mew, the `^` is added to the anchor's href and clicking on it produces this
image

**Review by jost-s — CHANGES_REQUESTED** [review]
Thanks for the fixes, the URL bug is still there

**Comment by mattyg** [comment]
> The URL bug is still there. Perhaps I didn't explain it well, when you write a URL like `^https://www.brave.com` and then do not enter a title and create the mew, the `^` is added to the anchor's href and clicking on it produces this

Oy, yeah I understood it. Looks like including a subdomain in the url breaks the regex :face_exhaling:

**Comment by mattyg** [comment]
Also just wanted to note that I think we could avoid a lot of this complexity in parsing on the front-end if we modified the data structure of a Mew in the DNA. Curious to get your thoughts on the alternative data structure I outlined here: https://github.com/artbrock/clutter/pull/44#issue-1527834729

If we're refactoring the DNAs anyway to follow the scaffolder patterns, maybe it makes sense to change the Mew data structure as well?

**Comment by jost-s** [comment]
> Also just wanted to note that I think we could avoid a lot of this complexity in parsing on the front-end if we modified the data structure of a Mew in the DNA. Curious to get your thoughts on the alternative data structure I outlined here: [#44 (comment)](https://github.com/artbrock/clutter/pull/44#issue-1527834729) @jost-s
> 
> If we're refactoring the DNAs anyway to follow the scaffolder patterns, maybe it makes sense to change the Mew data structure as well?

Yes, that's perfectly fine with me. Just run it by Arthur because he and Eric have spent quite some thought on the data structures.

Generally I feel like I'm not owning this project or the code, and it seems like you're taking on direction of it for the time being, so I'm fine with you making decisions.

**Comment by jost-s** [comment]
> > The URL bug is still there. Perhaps I didn't explain it well, when you write a URL like `^https://www.brave.com` and then do not enter a title and create the mew, the `^` is added to the anchor's href and clicking on it produces this
> 
> Oy, yeah I understood it. Looks like including a "www." subdomain in the url breaks the regex 😮‍💨

Now I can't get the input popup to enter the title for a URL at all for links starting with `^`. We can keep this simple IMO, for me there doesn't need to be a `www` in the pattern.
So it works when I enter a plain link without `^` and that could be enough, but then we need to write that in the tooltip too. Else it should work entering `^https://brave.com` and get the popup to enter the title.

**Comment by mattyg** [comment]
>  So it works when I enter a plain link without ^ and that could be enough, but then we need to write that in the tooltip too. Else it should work entering ^https://brave.com and get the popup to enter the title.

Yeah that was my intention -- just type a url and the input pops up. If you enter text in the input, it replaces the typed url with `^text` or `^[multi word text]`. If not, the typed url is treated as a link. 

But actually, thinking about it more -- It feels like very odd UX to type a url prefaced by `^https://example.com` and then enter the label in the input field, and then have the typed URL replaced with `^label`. In that case what does the `^` symbol represent? A raw url or a label? The meaning changes from when user types the text, to the resulting mew text.

Maybe it makes more sense to use the `^` like other tag symbols: as the *label* for a link. The user types `^label`, then enters the URL in the input field. That seems closer to UX of #hashtags and $cashtags people are used to, right? You enter the label and then it's converted into a link.

**Comment by jost-s** [comment]
I made it like this with the idea that a user will want to paste a URL. They go to some place and copy it there, then go to create a mew and paste the link. Optionally they can write a title.
As for hashtags and cashtags, there's no label and no difference between the tag and what's displayed.
Feel free to change it around as you see best fit.

**Comment by mattyg** [comment]
> I made it like this with the idea that a user will want to paste a URL. They go to some place and copy it there, then go to create a mew and paste the link. 

Yeah that makes sense. Okay let's just leave this open for now and I'll get some feedback from others before making a call. Sorry for all the trouble,

**Comment by mattyg** [comment]
Just noting that in the discussion today we decided to use the UX flow where a user types the link label and enters a URL in the input field. I will look over this PR again and decide if it makes sense to merge as-is and make that refactor in another PR, or just to modify this PR before merging.

**Comment by jost-s** [comment]
I've only updated the nix flake. Probably this flake was a couple of weeks old and in the meantime the referenced Holochain toolchain has been removed from the holochain-ci cachix account.

Now activating the Holochain dev env only took about a minute on a pipeline run.

So keep the flakes up to date by running `nix flake update`. That'll make sure you're pulling the Holochain dev tools from cachix instead of building them which takes ages.

Rust's target folder is also cached, but I think that plays a minor in the build process.

It took 13 mins for a test pipeline to run on Linux now, that's acceptable. MacOS is always rather sluggish in comparison, and the zome calls time out more easily. I'll set the timeout default to 60 s.

**Comment by jost-s** [comment]
Okay, done, and also refactored to use `runScenario` which will output errors correctly. (I'll bump to a default of 60 seconds for zome calls in the JS client. Until then it's set for every zome call.)

Nice, a re-run (unchanged zomes) of the Linux pipeline finished in 6 minutes. MacOS took 18 mins, not too bad.

The pipeline should be good for the time being.

**Pull request merged**
