### PR TITLE
Feat/holo hosting support

### PR DESCRIPTION
**Pull request by mattyg**
Fix support for holo hosting, with latest envoy server and @holo-host/web-sdk client.

To test this, you'll need to get a copy of the envoy server, and place it in the root of the directory as `holo-dev-server`.

### CODE REVIEW

**Comment by jost-s** [comment]
Hi @mattyg, maybe you can help me out here. I've compiled the holo dev server for macos and run the command `npm run start:holo:agent`. The console doesn't show errors anymore after initializing the keystore and rebuilding the happ.
However the web UI isn't able to connect and the browser console shows
image

Do you know why it cannot connect to the resolver?

**Comment by mattyg** [comment]
@jost-s Not sure I'm not getting that error - maybe a version mismatch? I'm on chaperone 0.1.0 and you're on 0.1.1. I assume you ran an npm install to get my fork of @holo-host/web-sdk?

Also it looks like I still have to refresh manually before it loads when starting via `npm run start:holo:agent` -- I think some error in COMB isn't bubbling up or something.

**Review by jost-s — APPROVED** [review]
Awesome! All I had to do was to switch to the 0.6.13-prerelease version of web-sdk from your fork and it was all groovy!

**Comment by mattyg** [comment]
> Awesome! All I had to do was to switch to the 0.6.13-prerelease version of web-sdk from your fork and it was all groovy!

huh weird. What do you mean by all groovy? For me I get an error in console `Uncaught (in promise) TypeError: u8a is undefined` and after signing into holo the app never loads because its expecting to have `client.myPubKey` which the holo version of AppAgentClient is missing.

Maybe I'll ask robbie for the latest envoy build and see if I can reproduce what you're seeing

**Comment by jost-s** [comment]
Oh, okay. I'll send you a recent build for Linux by email.

**Comment by mattyg** [comment]
okay great well it works now by using the npm package directly rather than the git branch, except that the iframe stylesheets are empty. 

Also I should try to handle the envoy, signup and cells loading to avoid needing to refresh. I'd also like to see if I can avoid the profiles errors thrown when we only have an anonymous agent.

**Comment by mattyg** [comment]
Okay I came up with a workaround to avoid the weird inconsistencies between the holo client and holochain client, such that we still only need 1 if statement to differentiate their setup. It resolves the need to refresh the page to complete the holo client setup. 

The stylesheet seems to be rendering properly as well for web-sdk version `0.6.13-prerelease`

**Pull request merged**
