### PR TITLE
Feat/feed polling

### PR DESCRIPTION
**Pull request by mattyg**
Partially addresses #56 

**Overview**
- add ui dependency `vue-request`
- refactor fetching mews feed to use SWRV pattern
   - polling for feeds
   - reload when window is refocused after at least 10 seconds away for feeds, 25 seconds away for other pages
   - extract common logic into higher-order components MewList and MewListItem, while dumb rendering components renamed to BaseMewList and BaseMewListItem
- remove mewsfeed pinia store and move logic directly into MewsFeed component
- remove pinia entirely
- add *all* data necessary to display mew into FeedMew: author profile, original author pubkey, original author profile, original mew deleted timestamp
- split TagsFeed into 3 components for each tag type
- standardize naming of emit events and add more events for greater specificity
- move stores/client & stores/profiles into utils/

### CODE REVIEW

**Comment by mattyg** [comment]
Heads up this one isn't quite ready - seems like I can't revert to draft

**Review by jost-s — COMMENTED** [review]
I'm so used to publishing mews with command+return that I just noticed that it's possible to submit the mew with less than 10 characters, which will show a cryptic error toast at the bottom of the screen.

**Review by jost-s — APPROVED** [review]
Fabulous, this is so awesome!

**Comment by jost-s** [comment]
I'm wondering should there be polling for the yarn view too?

**Comment by mattyg** [comment]
> I'm wondering should there be polling for the yarn view too?

yes it's also polling every 120s

**Pull request merged**
