### PR TITLE
Fix/profile popup data incorrect

### LINKED ISSUE #195: Profile popup on mentions inconsistently shows incorrect profile data
**Steps to reproduce**
- navigate to feed
- create a mew mentioning user 1
- create a mew mentioning user 2
- create several more mews mentioning user 2
- view the profile popups for all the mentions, consistently at least one will show the incorrect profile name & data (excluding avatar and following status)

This is the result of a bug in @tanstack/vue-query where the queryKey used to retrieve data from the cache is not reactively updating. The queryKey for agent profile data includes the agent's pub key, which is passed as a component prop.

There is a PR open for a fix https://github.com/TanStack/query/pull/5934

### LINKED ISSUE #206: Hashtags list displays incorrect mew
> A mew shows up in what seems to be the wrong #hashtag category: a tweet about #Holochain and #MewsFeed shows up in #regen
image

### PR DESCRIPTION
**Pull request by mattyg**
Resolves #195 
Resolves #206

### CODE REVIEW

**Comment by jost-s** [comment]
Hashtag list is still displaying incorrect mew:
image

**Review by jost-s — CHANGES_REQUESTED** [review]
see comments above

**Comment by mattyg** [comment]
> see comments above

did you run `npm install` -- there are updates to deps that had a bug related to this issue. I can't reproduce what you're seeing

**Comment by jost-s** [comment]
True, I hadn't. Works fine now

**Review by jost-s — APPROVED** [review]

**Pull request merged**
