### PR TITLE
Fix/profile not found errors

### LINKED ISSUE #188: "Profile Not Found" errors upon searching for names
This may be the result of having received gossiped search index links of the agent but not having yet received gossiped profile info from the agent.

The UX should either exclude those agents from search results and not show errors, or else gracefully degrade the results (i.e. display the agentpubkey rather than the profile picture and handle).

### PR DESCRIPTION
**Pull request by mattyg**
Resolves #188 

Don't require profile for any component, instead, gracefully degrade to displaying agent pub key in place of profile name

### CODE REVIEW

**Review by jost-s — COMMENTED** [review]
Is this abbreviation intentional?
image

**Comment by jost-s** [comment]
A related bug, when I'm on agent A's profile page and click on "Follow", the "Followers" count increases immediately, but when I click on it, the profile isn't displayed.
image

image

**Review by jost-s — COMMENTED** [review]
These filters aren't needed any longer https://github.com/GeekGene/mewsfeed/pull/225/files#diff-a2957e428e699ad1bdd854cf0f707ce494ae491aaaca72e4b5cf8c72a6127229L92

https://github.com/GeekGene/mewsfeed/pull/225/files#diff-73289534eedce049cb269935139a2a58180c855a003fcc9a60d008b6093767f3L107

**Comment by mattyg** [comment]
> Is this abbreviation intentional?

yes, but it doesn't make sense for that component -- I'll remove it.

> A related bug, when I'm on agent A's profile page and click on "Follow", the "Followers" count increases immediately, but when I click on it, the profile isn't displayed.

good catch -- fixed

> These filters aren't needed any longer https://github.com/GeekGene/mewsfeed/pull/225/files#diff-a2957e428e699ad1bdd854cf0f707ce494ae491aaaca72e4b5cf8c72a6127229L92
>
> https://github.com/GeekGene/mewsfeed/pull/225/files#diff-73289534eedce049cb269935139a2a58180c855a003fcc9a60d008b6093767f3L107

I think these links aren't directing me to the line -- what are you referring to?

**Comment by jost-s** [comment]
> I think these links aren't directing me to the line -- what are you referring to?

It's the next line actually `return agentProfiles.filter(Boolean) as AgentProfile[];`. Before there were `null` values, but now there'll be an incomplete profile, so filtering by `Boolean` doesn't change anything any longer.

**Review by jost-s — COMMENTED** [review]
The pub key isn't abbreviated any longer. Please have a look at what's happening here. It could be because I messed with the load creators function to not load the profile for testing this:

```typescript
const agentProfiles = await Promise.all(
    agents.map(async (agentPubKey) => {
      let profile;
      try {
        // profile = await profilesStore.client.getAgentProfile(agentPubKey);
      } catch (error) {
        console.error(error);
      }

      return {
        agentPubKey,
        profile,
      } as unknown as AgentProfile;
    })
  );
```

https://github.com/GeekGene/mewsfeed/assets/28270981/1a3d990d-9bbe-4ce1-8de0-b7ffacaf4c55

**Comment by mattyg** [comment]
I can't reproduce the issues seen the video. Going to merge for now to get a release out and we can see if they arise again.

**Comment by jost-s** [comment]
Cool, yeah

**Pull request merged**
