### PR TITLE
feat(ui): persist all data to localStorage

### PR DESCRIPTION
**Pull request by mattyg**
- add ui dependency `pinia-plugin-persistedstate`
- use localStorage as cache in component SWRV pattern requests
- use pinia notifications store as cache for notifications SWRV request
- use localStorage to persist pinia store

### CODE REVIEW

**Review by jost-s — COMMENTED** [review]
The toasts at the bottom are only showing for less than a second. I suggest to increase that to 2-3 seconds.

**Review by jost-s — COMMENTED** [review]
Another likely unrelated issue, when I'm on the feed page (route "/") and refresh the page, I'm rerouted to "/discover".

**Review by jost-s — APPROVED** [review]
Storing and caching looks good to me.

**Comment by mattyg** [comment]
> The toasts at the bottom are only showing for less than a second. I suggest to increase that to 2-3 seconds.

Idk I feel like that's too long.

**Comment by jost-s** [comment]
> Idk I feel like that's too long for success messages -- maybe just for errors.

With less than a second you need to be expecting where the message appears and read for your life =D

**Comment by mattyg** [comment]
> > Idk I feel like that's too long for success messages -- maybe just for errors.
> 
> With less than a second you need to be expecting where the message appears and read for your life =D

yeah but the success messages are all 1 word, just confirming success the action you already took (and already know the outcome to). Idk maybe we can get some more feedback and see what people think.

**Pull request merged**
